### ISSUE TITLE
ReferenceError: Insta is not defined - Insta = new Instagram()

### ISSUE THREAD

**Issue by Angelk90** [yatsenkolesh/instagram-nodejs#20]
I installed the module via the command: `Npm and instagram-nodejs-without-api -save`
The command:` yarn add instagram-nodejs-without-api` I'm having problems.

Installation is successful, I run the following error:
```
/var/lib/openshift/..../app-root/runtime/repo/node_modules/instagram-nodejs-without-api/instagram.js:589
Insta = new Instagram()
      ^
ReferenceError: Insta is not defined
    at Object.<anonymous> (/var/lib/openshift/..../app-root/runtime/repo/node_modules/instagram-nodejs-without-api/instagram.js:589:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/openshift/..../app-root/runtime/repo/app.js:9:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/openshift/..../app-root/runtime/repo/start.js:39:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Then I'm going to open the file: node_modules / instagram-nodejs-without-api / instagram.js
I agree that there are in the final part of the script code lines in addition:
```
Insta = new Instagram ()
....
....
...
```

So I'm going to check the hosted file on github, I see that the two scripts in js are different, for these final code lines and also the beginning part are different:
`Module.exports = class Instagram` ---------> on github
`Class Instagram` ---------> by installing npm

Try replacing the script with that on github, not the same problem, as indicated by the title.

Also, the proper way to use the form should not be:
`Var Instagram = require ('instagram-nodejs-without-api');
`
Anyway, even without ever asking the library for the initial problem.

@yatsenkolesh: How can I fix the problem?

**Comment by yatsenkolesh** [comment]
Hey. Thank you for the issue. You choose the true way to resolve this problem. I will fix this problem in during several days and try to update API with receiving followers too in during several weeks.

**Comment by Angelk90** [comment]
@yatsenkolesh: I recommend you check it out before, I noticed that they changed something to getCsrfToken recovery.
