### ISSUE TITLE
How to use? Show working example.

### ISSUE THREAD

**Issue by ptflp** [yatsenkolesh/instagram-nodejs#28]
Something like this
`yarn add instagram-nodejs-without-api`
and then create file index.js ?
with code: 
```
Instagram = new Instagram()
 
 
Instagram.getCsrfToken().then((csrf) =>
{
  Instagram.csrfToken = csrf;
}).then(() =>
{
  Instagram.auth('inst-your-username', 'inst-your-password').then(sessionId =>
  {
    Instagram.sessionId = sessionId
 
    Instagram.getUserDataByUsername('username-for-get').then((t) =>
    {
      Instagram.getUserFollowers(JSON.parse(t).graphql.user.id).then((t) =>
      {
        console.log(t); // - instagram followers for user "username-for-get"
      })
    })
 
  })
})
```
and then take this error:
```
PS C:\Users\ptflp\insta> node index.js
C:\Users\ptflp\insta\index.js:1
(function (exports, require, module, __filename, __dirname) { Instagram = new Instagram()
                                                              ^

ReferenceError: Instagram is not defined
    at Object.<anonymous> (C:\Users\ptflp\insta\index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```

**Comment by alvin-milton** [comment]
I found this:
https://www.npmjs.com/package/node-instagram

Might be pertinent. Will try soon.

**Comment by yatsenkolesh** [comment]
Hello. You need to declare Instagram client class witth import like:

const Instagram = require('instagram-nodejs-without-api');

**Comment by philberhane** [comment]
Hey I tried this and now it says it cannot find the instagram-nodejs-without-api module :(

**Comment by philberhane** [comment]
NVM. Figured it out. I thought the package was already installed but it wasn't. ALso, it wouldn't let me install the package because it's the same name as the project, so I had to change the project name

**Comment by yatsenkolesh** [comment]
Thank you for you issue. Closed.
