### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by Minaeskandar** [yatsenkolesh/instagram-nodejs#35]
Im trying ro run the script with cmd and node.js but nothing is working? How should i run it?

**Comment by juanjoayala01** [comment]
+1 here xd

**Comment by yatsenkolesh** [comment]
Hello, guys ! The fix is an in progress.

**Comment by yatsenkolesh** [comment]
I will notify you when we fix it (soon)

**Comment by juanjoayala01** [comment]
thanks!

**Comment by yatsenkolesh** [comment]
We are fixed!  I updated the version. Try to use 1.0.3, but if u will have challenge required exception - push me.

**Comment by Minaeskandar** [comment]
how do you run the script? I created a file named index.js and put the code inside of it, but I don't know how to run it through cmd? Help

**Comment by Minaeskandar** [comment]
when i run the script i get this error.

Instagram authentication failed (challenge required erro)
TypeError: Cannot read property '1' of null
    at C:\Users\minae\Desktop\instagram-nodejs-master\node_modules\instagram-nodejs-without-api\instagram.js:76:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Minaeskandar** [comment]
`Instagram authentication failed (challenge required erro)
TypeError: Cannot read property '1' of null
    at C:\Users\minae\Desktop\instagram-nodejs-master\node_modules\instagram-nodejs-without-api\instagram.js:76:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by emanuelevivoli** [comment]
i have the same error

**Comment by emanuelevivoli** [comment]
I make some changes and now the `Instagram authentication failed (challenge required erro)` disappeared!

- Use a real Instagram account name instead of `username-for-get` line 14 in the example written in the README.md
- Try the #40
