### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by emanuelevivoli** [yatsenkolesh/instagram-nodejs#41]
When I try `insta.getUserDataById()` I get this error:
```
(node:11743) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://www.instagram.com/query/ reason: Unexpected end of JSON input
    at myproject/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I tried to do reverse engineering but I'm young in node and i can't understand where I'm wrong.

**Comment by volkorros** [comment]
@emanuelevivoli Hello. I also faced this issue and also tried to do reverse engineering but without any successful results :( @yatsenkolesh please have a look!
