### ISSUE TITLE
challenge required erro

### ISSUE THREAD

**Issue by yousef94alkhateeb** [yatsenkolesh/instagram-nodejs#42]
Instagram authentication failed (challenge required erro)
TypeError: Cannot read property '1' of null
    at C:\Program Files\nodejs\node_modules\npm\node_modules\instagram-nodejs-without-api\instagram.js:76:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by yatsenkolesh** [comment]
Hello, guys. You are need to change account

**Comment by rodrigueslg** [comment]
I tried with three differents accounts and still getting the same error

**Comment by aeroxy** [comment]
I also ran into this issue.

`Instagram authentication failed (challenge required erro)` from `Instagram.auth('username', 'password')`

**Comment by benkaiser** [comment]
Looks like it's fixed in master but not pushed to NPM.
See commit: https://github.com/yatsenkolesh/instagram-nodejs/commit/ff03cd2de5476411262c442be59fb7ebd33ae046

**Comment by yatsenkolesh** [comment]
@benkaiser I will publish it with your commit.

**Comment by benkaiser** [comment]
Thanks mate!

**Comment by benkaiser** [comment]
Btw @yatsenkolesh it seems following the code snippet from the readme also throws for me on getting the list of followers for a user (I think Instagram deprecated the /query/ endpoint, and you have to use /graphql/query and it has a slightly different API.

I don't know if I have any time today, but I'll try and get around to submitting a PR for fixing that too.

**Comment by yatsenkolesh** [comment]
It’s will great !

**Comment by Hazantip** [comment]
> Looks like it's fixed in master but not pushed to NPM.
> See commit: [ff03cd2](https://github.com/yatsenkolesh/instagram-nodejs/commit/ff03cd2de5476411262c442be59fb7ebd33ae046)

@yatsenkolesh npm still 1.0.3

**Comment by yatsenkolesh** [comment]
@Hazantip sorry for the delay. I published 1.2.0.
